# Generated by Django 2.1.7 on 2019-04-15 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Urldetails',
            fields=[
                ('user_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('url_nickname', models.CharField(max_length=200, null=True)),
                ('link', models.TextField(null=True)),
                ('sessionid', models.TextField(null=True)),
                ('createddate', models.DateTimeField(null=True)),
                ('status', models.BooleanField(default=1)),
            ],
            options={
                'db_table': 'url_details',
            },
        ),
    ]
